config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#home'
  resources :cocktails, only: [ :index, :show, :create, :new] do
    resources :doses, only: [:create, :new] do
    end
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def home
  end

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @dose = Dose.new
    @dose.cocktail = @cocktail
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/cocktails/home.html.erb
<div class="home-bg">
  <%= link_to "OPEN THE BAR", cocktails_path, class: "btn btn-home" %>
</div>

app/views/cocktails/index.html.erb
<div class="container">

  <%= render './shared/navbar.html.erb' %>

  <div class="container">
    <div class="row row-cols-3">
      <% @cocktails.each do |cocktail| %>
            <div class="col">
              <div class="card" style="width: 18rem;">
                <img src="https://source.unsplash.com/featured/?cocktail/300x300" class="card-img" alt="coktail">
                <div class="card-body">
                  <h5 class="card-title"> <%= cocktail.name%></h5>
                  <p class="card-text"> <%= link_to "Details", cocktail_path(cocktail), class: "btn btn-index" %>
                  </p>
                </div>
              </div>
            </div>
      <% end %>
    </div>
  </div>


</div>


  

app/views/cocktails/new.html.erb
<div class="container bg-new">

  <div class="form-card">
    <h1>Create your cocktail</h1>

    <%= simple_form_for(@cocktail) do |f| %>
      <%= f.input :name, 
                  label: "Please, enter below the name of your cocktail" %>
      <%= f.simple_fields_for :doses do |g| %>
      <%= g.input :description, 
                  label: 'Add a description' %>
      <%= g.input :ingredient_id,
                      label: "Choose ingredients",
                      as: :check_boxes,
                      include_blank: :false,
                      collection: Ingredient.all %>
      <% end %>
      <%= f.button :submit, "Save", class: 'btn btn-index' %>
    <% end %>
    
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container-show">

  <div class="card-show">

    <img src="https://source.unsplash.com/featured/?cocktail" class="card-img" alt="coktail">

    <div class="card-img-overlay">
      <%= link_to "Create a dose", new_cocktail_dose_path(@cocktail), class: "btn btn-show" %>
      <%= link_to "Back to cocktails", cocktails_path, class: "btn btn-show" %>

      <h1 class="card-title"> <%= @cocktail.name %> </h1>
        <p> Serve in a <%= @cocktail.glass %> glass </p>

      <div class="card-text">
        <h3>Recipe</h3>
        <p> Add <%= @cocktail.garnish %> garnish </p>
        <p> <%= @cocktail.preparation %> </p>
      
        <h3>Description</h3>
          <% @cocktail.doses.each do |dose| %>
            <p> Fill with <%= dose.description %> </p>
            <%= link_to "🗑️",
                    dose_path(dose),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
          <% end %>

          <% @cocktail.ingredients.each do |ingredient| %>
            <%= ingredient.name %>
            <%= ingredient.label %>
            <%= ingredient.special %>
            <%= ingredient.amount %>
            <%= ingredient.unit %>
          <% end %>
      </div>
        
    </div>
    
  </div>
    
</div>

app/views/doses/new.html.erb
<div class="container">

  <div class="form-card"> 
    <h1>Customize your cocktail</h1>

    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.input :description,
                  label: "Add a description" %>
      <%= f.simple_fields_for :doses do |g| %>
        <%= g.input :ingredient_id,
                      label: "Choose ingredients",
                      as: :check_boxes,
                      include_blank: :false,
                      collection: Ingredient.all %>
      <% end %>
      <%= f.button :submit, "Save", class: 'btn btn-index' %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <title>Tales of Fancy - Make Your Own Luxury Cocktails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'logo.png' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
      <%= simple_form_for :search, url: cocktails_path, method: :get do |f| %>
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="search[query]" id="search_query" />
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i> Search
          </button>
        </div>
      <% end %>
  </div>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag 'avatar.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "New cocktail", new_cocktail_path, class: "dropdown-item" %>
            <%= link_to "My cocktails", cocktails_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>